### ISSUE TITLE
S3 - (5) Rediseñar todo la estructura de página principal

### ISSUE THREAD

**Issue by wilmereleon** [wilmereleon/W-lmerE_Le-n_BlogM-sica#22]
Se requiere rediseñar toda la pagina de Welle y generar los contenidos demos de cada uno de los contenedores de los mismos:
**_ACTUALMENTE_**------------------------------------------------------->**_RESULTADO ESPERADO_**
![Prototipo de página Welle (antes-después)](https://github.com/wilmereleon/W-lmerE_Le-n_BlogM-sica/assets/42726764/6e94cf81-899d-4c38-ab87-60b670993bbd)
El prototipo fue creado en Figma; para mayor precisión de los detalles solicitados, se añade el siguiente enlace de visualización: 
[Prototipo en Figma](https://www.figma.com/file/6hzqaVqmtSxdr6LaGy8Ien/Prototipo-de-p%C3%A1gina-Welle-(antes-despu%C3%A9s)?type=design&node-id=1%3A5&mode=design&t=dLB4cm7qWMH4zt1H-1)
El rediseño de la página inicial requiere lo siguiente:

- [ ] Generar los contenedores especificados en la imagen.
- [ ] Generar los enlaces a cada uno de los contenedores de noticias.
- [ ] Generar contenidos de acuerdo con la sección noticiosa a la que pertenece (Música, Cocina y Viajes); por lo tanto, cada contenido adopta las características de dicha identidad.
- [ ] Cambiar las fotos de la sección de desplazamiento de noticias (se mantiene la de Gypsy & The Cat ─Música─, se añade una foto de una receta ─Cocina─ y una foto de Italia como destino ─Viajes─). Al momento de desplazar la noticia con los botones del centro de la foto, también cambia la descripción que aparece en el contendedor de la parte inferior de la foto (el ejemplo de la descripción está con la noticia de Música que describe al autor Andrés Rengifo y una sinopsis breve de la noticia de la separación de Gypsy & The Cat).

**Comment by wilmereleon** [comment]
Este rediseño se hace para el proceso PSP3 (desarrollo cíclico). Usar el script plantilla PSP3, de Process Dashboard

**Comment by wilmereleon** [comment]
Los contenedores más pequeños tiene que enlazar a otras páginas. La sección de Viajes (Destinos del mes en Welle) con contenedores independientes que enlazan a contenidos en cada una de sus banderas (4 enlaces), al igual que cada contenedor de cada sección. Revisar documentación de Bootstrap para el diseño de difuminados en los fondos de los títulos y distribución de las rejillas: [Rejillas y contenedores en Grid](https://getbootstrap.com/docs/5.3/layout/grid/), Glutters: [Glutters](https://getbootstrap.com/docs/5.3/layout/gutters/) y Nesting: [Nesting](https://getbootstrap.com/docs/5.3/layout/css-grid/)

**Comment by wilmereleon** [comment]
Ejemplos de contenedores imagen-título: [Bootstrap and masonry](https://getbootstrap.com/docs/5.3/examples/masonry/) y como deberia quedar el comportamiento de los contenedores con fondo difuminado para el título: [blogzine ejemplo](https://themes.getbootstrap.com/preview/?theme_id=92520)

**Comment by wilmereleon** [comment]
@Vst75 , revisar video [Aprende Bootstrap 5](https://youtu.be/QCw0L6FupQ0)
